steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/vote-route:$COMMIT_SHA', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/vote-route:$COMMIT_SHA']

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vote-route'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/vote-route:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/vote-route:$COMMIT_SHA'

substitutions:
  _REGION: us-central1
  _REPO_NAME: vote-route-repo
